# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1d47b6986ce7be25dd07f74d1aa9c77afe9b4fe18a2a832bec83089bd4ba66f5d69c3496834f7f3706710cfe6f573464d0ef642debaebd6804b940a962f6187

test:
  secret_key_base: 4a2b3086cd4a7f812c463daa4bbe10fd4c07a3aeabfd9590f6f060cce5b0905b4beb28c9202407d6f97e2eb5adca8503fc6abc02ebdf634f519a38a7e4346ccb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
